set universal testCaseName to "TD_2739_dashboardMenuValidation"
"WPO/WPO_CommonHandlers".readTestData universal testCaseName
--"WPO/WPO_utilities".validateWhetherScreenIsOnDashBoardOrNot
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"WPO/WPO_CommonHandlers".dashboardMenuValidationWPO universal data.userName,universal data.passWord,universal data.moduleName,universal data.titleofModule,universal data.profileName,universal data.noDataFoundtertiaryMenuOfMenu,universal data.dataFoundtertiaryMenuOfMenu,universal data.menu,universal data.subMenuOfMenu
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat
