set universal testCaseName to "TD_2740_validationOfMenus"
"WPO/WPO_CommonHandlers".readTestData universal testCaseName
"WPO/WPO_utilities".validateWhetherScreenIsOnDashBoardOrNot
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"WPO/WPO_CommonHandlers".validationOfAllTheMenusWPO universal data.profileName,universal data.preferencename,universal data.preferencevalue,universal data.menu,universal data.subMenuOfMenu,universal data.tertiaryMenuOfMenu
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard 
	put "Done" into universal data.run_Status
end repeat
