set universal testCaseName to "TD_2733_dashboardMenuValidation"
"PORS/PORS_CommonHandlers".readTestData universal testCaseName
"PORS/PORS_utilities".validateWhetherScreenIsOnDashBoardOrNot
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"PORS/PORS_CommonHandlers".dashboardMenuValidation universal data.userName,universal data.passWord,universal data.tails,universal data.organization,universal data.supplier
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat