set universal testCaseName to "TD_1787_DownloadAll"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testCaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
(*"SC2_Login/logInAndLogout_commonHandlers".launchURL "Chrome",universal testData.SC2ApplicationURL
"SC2_Login/logInAndLogout_commonHandlers".logInToSC2App, universal testData.userName,universal testData.passWord*)
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"Planning_Dashboard/dashBoard_commonHandlers".verifyApplicationIsAbleToAccessTheUnderlyingS3Bucket
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
end repeat