set universal testCaseName to "TD_1906_SetPreference"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testCaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"Planning_Dashboard/dashBoard_commonHandlers".setPreferences universal data.requesterName
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat


