set universal testcaseName to "TD_1953_importExportValidation"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase
repeat number of items of universal data times
	"Planning_F&C/ForeCast/foreCast_commonHandlers".importExportValidationWithMissingData universal data.supplierName
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat