#Download Full Horizon Data in Planner Horizontal View
set universal testcaseName to "TD_2198_DownloadFullHorizon"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
log universal data
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"Planning_F&C/PlannerHorizontalView/forecastHorizontal_commonHandlers".downloadFullHorizonDataInPHV  universal data.partNumber
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat