#Mass Upload and UI update adj in Planner Horizontal View (Add New WW) Part 1
set universal testcaseName to "TD_2160_massUploadAddNewWW"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase
repeat number of items of universal data times
	#Mass Upload and UI update adj in Planner Horizontal View (Add New WW) Part 1
	"Planning_F&C/PlannerHorizontalView/forecastHorizontal_commonHandlers".massUploadPHViewAddNewWWPart1
	#navigating to the Dashboard
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat