set universal testCaseName to "TD_2760_validationOfMenus"
"SMI/SMI_CommonHandlers".readTestData universal testCaseName
"SMI/SMI_utilities".validateWhetherScreenIsOnDashBoardOrNot
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"SMI/SMI_CommonHandlers".validationOfAllTheMenusSMI universal data.userName,universal data.passWord,universal data.tails,universal data.organization,universal data.supplier
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat
