#F&C escalation update should consider about pending qty as well in Vertical View
set universal testcaseName to "TD_2197_EscalationHistoryPH"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
#validating  that whethe the Application is on the DashBoard or not 
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
#validating the Control phase
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase,universal data.controlPhase1
#F&C escalation update should consider about pending qty as well in Vertical View
"review&Commit_F&C/PlannerHorizontalView/forecastHorizontal_commonHandlers".viewEscalationRequestHistoryInPlannerHorizontalView
#After the Execution clicling on the Dashboard
"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
put "Done" into universal data.run_Status