set universal testcaseName to "TD_2089_EscalationPORequired"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase,universal data.controlPhase1
repeat number of items of universal data times
	"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
	"review&Commit_F&C/ForeCast/foreCast_commonHandlers". ValidatingPORequiredEmailAfter12pmMYT universal data.partNumber, universal data.categoryInForecast
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat