set universal testcaseName to "TD_2348_ PRMultiCommits"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"review&Commit_F&C/ForeCast/foreCast_commonHandlers".plannerReviewMultiCommitsUIandexport 
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat

