set universal testcaseName to "TD_1979_EscalationInWorkWeekUI"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase,universal data.controlPhase1
repeat number of items of universal data times
	"review&Commit_F&C/ForeCast/foreCast_commonHandlers".raiseEscalationViaAddNewWorkWeekInUI universal data.partNumber,universal data.categoryInForecast,universal data.AdjustmentPositiveValue,universal data.EscalationReason
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat

