set universal testcaseName to "TD_1974_reEscalationSubmitted"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase,universal data.controlPhase1
repeat number of items of universal data times
	"review&Commit_F&C/ForeCast/foreCast_commonHandlers".reEscalationchangesOnSubmittedRequest  universal data.partNumber,universal data.categoryInForecast,universal data.EscalationReason,universal data.PlannerRemarks,universal data.ManagerEMail,universal data.checkBoxText
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat

