set universal testcaseName to "TD_2587_ SOViewExportedFile2"
"SC2_CommonActions/sc2CommonHandlers".readTestData universal testcaseName
"SC2_CommonActions/sc2CommonHandlers".validateWhetherScreenIsOnDashBoardOrNot
"SC2_CommonActions/sc2CommonHandlers".validateControlPhase universal data.controlPhase,universal data.controlPhase1
repeat number of items of universal data times
	set universal testData to item repeatIndex() of universal data
	"review&Commit_F&C/ForeCast/foreCast_commonHandlers". SOViewExportedFileChecking2 universal data.fileName
	"SC2_CommonActions/sc2CommonHandlers".navigateToDashboard
	put "Done" into universal data.run_Status
end repeat

